server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.88.128
    username: taotao
    password: taotao
    virtual-host: /taotao
  redis:
    host: 192.168.88.128
taotao:
  sms:
    accessKeyId: LTAI4FkBpYg435XnJd9MRF6v # 你自己的accessKeyId
    accessKeySecret: CntYYhCURpQ9ZCbyitdjED0SrDgfVB # 你自己的AccessKeySecret
    signName: taotao商城 # 签名名称
    verifyCodeTemplate: SMS_177355065 # 模板名称