spring:
  application:
    name: page-server
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.88.128
    username: taotao
    password: taotao
    virtual-host: /taotao
server:
  port: 8084
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka