server:
  port: 10010
spring:
  application:
    name: taotao-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5
zuul:
  routes:
    item-route:
      path: item-service
      url: /item/**
      strip-prefix: false